### ISSUE TITLE
missing tun device

### ISSUE THREAD

**Issue by danny-waite** [offlinehacker/openvpn-k8s#4]
Hey,

Was just trying this out, I get the following error:

ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such device (errno=19)

I've added the following to the container spec

```
capabilities:
  add:
    - NET_ADMIN
```

and also tried adding `privileged: true` but just can't seem to get this working.  Wondering how your environment differs to mine.

I'm using GKE, Kubernetes Version 1.3.5 

Any hints appreciated.

**Comment by danny-waite** [comment]
An update:

I've tested this using minikube and this works so it looks like the issue is specifically with Google Container Engine, I'll try to dig further

**Comment by offlinehacker** [comment]
I have no idea, it works for me on gke 1.2 verison, but only as privileged.

**Comment by offlinehacker** [comment]
Can you try this in pod:

```
mkdir /dev/net (if it doesn't exist already)
mknod /dev/net/tun c 10 200
```

running as privileged

**Comment by danny-waite** [comment]
Hi Jaka, yeah will try, issue is that the pod dies after a little while so hard to exec into it...

**Comment by offlinehacker** [comment]
Create a different pod with busybox image and run sh -c "mkdir -p /dev/net
&& mknod /dev/net/tun c 10 200 && tail -f" as command.

**Comment by danny-waite** [comment]
ah ok, just to confirm, do you mean run another container (with busybox) inside the same pod?

**Comment by danny-waite** [comment]
Well I just created a new busybox pod like so:

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: busybox-net
  labels:
    name: busybox-net
spec:
  replicas: 1
  selector:
    name: busybox-net
  template:
    metadata:
      labels:
        name: busybox-net
    spec:
      containers:
        - name: busybox-net
          image: busybox
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          args:
            - sleep
            - "1000000"
```

and then `kubectl exec -it busybox-net-wvh11 sh`

both `mkdir /dev/net` and `mknod /dev/net/tun c 10 200` were successful.

Strangely I see you have these in you entrypoint.sh however maybe the image that sit on docker hub does not have these?
